azure_dbt_project_uber:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: AZURE_DBT_ROLE
      warehouse: AZURE_WH
      database: AZURE_DB
      schema: AZURE_SCHEMA
      account: ''
      user: ''
