name: data_pipeline
version: 1.0.0
config-version: 2
profile: data_pipeline
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  data_pipeline:
    staging:
        +materialized: view
        snowflake_warehouse: dbt_wh
    marts:
        +materialized: table
        snowflake_warehouse: dbt_wh