data_pipeline:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: DBT_ROLE
      warehouse: DBT_WH
      database: DBT_DB
      schema: DBT_SCHEMA
      account: 'can be empty'
      user: 'can be empty'
